name: Release version

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  release_zip_file:
    name: Prepare release asset
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v7

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Get version
        id: version
        uses: home-assistant/actions/helpers/version@master

      - name: Set manifest version number
        run: |
          python3 .github/scripts/update_version.py --version ${{ steps.version.outputs.version }}

      - name: Create zip
        run: |
          cd custom_components/fritzbox_voicemail
          zip -r fritzbox_voicemail.zip ./

      - name: Upload zip to release
        uses: svenstaro/upload-release-action@29e53e917877a24fad85510ded594ab3c9ca12de
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: custom_components/fritzbox_voicemail/fritzbox_voicemail.zip
          asset_name: fritzbox_voicemail.zip
          tag: ${{ github.event.release.tag_name }}
          overwrite: true
